### PR TITLE
Make stub_with work with skip_optional_callbacks

### LINKED ISSUE #95: Mox.stub_with/2 does not work with skip_optional_callbacks
Using `Mox.stub_with/2` in combination with skipping optional callbacks will result into an `(ArgumentError) unknown function XXX for mock XXX` error. Looking at the Mox code for `stub_with` it will take all callbacks instead of skipping those as defined in `skip_optional_callbacks`. 

A simple way to reproduce this:

```
defmodule MyBehaviour do
  @callback always(any()) :: any()
  @callback optional(any()) :: any()

  @optional_callbacks optional: 1
end

defmodule MyStub do
  @behaviour MyBehaviour
  def always(_), do: true
end

Mox.defmock(
  MyMock,
  for: MyBehaviour,
  skip_optional_callbacks: true
)
```

Doing:

```
MyMock |> stub_with(MyStub)
```

In a test will result in the following error:

```
 ** (ArgumentError) unknown function optional/1 for mock MyMock
     code: MyMock |> stub_with(MyStub)
     stacktrace:
       (mox 0.5.2) lib/mox.ex:546: Mox.add_expectation!/4
       (mox 0.5.2) lib/mox.ex:477: Mox.stub/3
       (mox 0.5.2) lib/mox.ex:528: anonymous fn/4 in Mox.stub_with/2
       (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
       (mox 0.5.2) lib/mox.ex:525: Mox.stub_with/2
       test/helper/my_test.exs:8: (test)
```

### PR DESCRIPTION
**Pull request by flurin**
Checks if the mock actually exports the function before it defines the stub. Fixes #95

### CODE REVIEW

File: lib/mox.ex [hunk 1]
```diff
@@ -524,7 +524,9 @@ defmodule Mox do
 
     for behaviour <- behaviours,
         {fun, arity} <- behaviour.behaviour_info(:callbacks) do
-      stub(mock, fun, :erlang.make_fun(module, fun, arity))
+      if function_exported?(mock, fun, arity) do
```
Comment (josevalim) [inline lib/mox.ex:527]: We should only skip if they are optional though. Otherwise we can stop raising for functions that are required .

Comment (josevalim) [inline lib/mox.ex:527]: Something along these lines:

    for behaviour <- behaviours,
        optional = behaviour.behaviour_info(:optional_callbacks),
        {fun, arity} <- behaviour.behaviour_info(:callbacks) do
      if function_exported?(mock, fun, arity) or {fun, arity} not in optional do

We should add a test that `stub_with` fails when some non-optional callback is missing.

Comment (flurin) [reply lib/mox.ex:527]: I'm not sure because this checks if the mock function had been defined on the mock. So when you use `skip_optional_callbacks` with a specific set of callbacks it still works correctly. 

Just checking if it's optional wouldn't cover that, right?

Comment (flurin) [reply lib/mox.ex:527]: I agree that you should always implement the full behaviour in the Stub module, but enforcing this would possibly break a lot of current usage.  Currently this test succeeds:

```
    defmodule PartialCalcImplementation do
      @behaviour Calculator
      def add(x, y), do: x + y
    end

    test "partial" do
      in_all_modes(fn ->
        stub_with(CalcMock, PartialCalcImplementation)
        assert CalcMock.add(1, 2) == 3

        assert_raise UndefinedFunctionError, fn ->
          assert CalcMock.mult(3, 4)
        end
      end)
    end
```

Comment (flurin) [reply lib/mox.ex:527]: I'd be happy to change that you can only stub full behaviour implementations of course.

Comment (josevalim) [reply lib/mox.ex]: I see, I misunderstood. Looks good as is then!

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
